[tox]
envlist = py{39,310,311,312}-django{42}
recreate = True

[testenv]
basepython =
    py39: python3.9
    py310: python3.10
    py311: python3.11
    py312: python3.12
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements-test.txt
    django32: Django>=3.2,<3.3
    django42: Django>=4.2,<5.0
    -e .  # Install the current package in editable mode
commands = django-admin test --traceback --settings=chroniker.tests.settings chroniker.tests.tests.JobTestCase{env:TESTNAME:}
