# Generated by Django 3.0.4 on 2020-04-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chroniker', '0002_auto_20190415_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('value', models.TextField(verbose_name='Value')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chroniker.Job')),
            ],
            options={
                'unique_together': {('job', 'name', 'value')},
            },
        ),
    ]
