# Generated by Django 3.0.9 on 2020-09-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniker', '0002_auto_20190415_0925'),
    ]

    operations = [
        migrations.RenameField(
            'Job', 'monitor_description', 'description'
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text="An explanation of the job's purpose.",
                                   null=True, verbose_name='description'),
        ),
    ]
