# Generated by Django 3.0.6 on 2020-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniker', '0003_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='description'),
        ),
    ]
