# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniker', '0004_auto_20240328_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jitter_seconds',
            field=models.PositiveIntegerField(default=0, help_text='If given, a random offset of up to this many seconds is added to each scheduled run time.<br/>Useful for spreading load when several jobs or servers would otherwise fire at the same instant.<br/>A value of 0 disables jitter.', verbose_name='jitter seconds'),
        ),
    ]
