# Generated by Django 3.0.5 on 2020-07-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniker', '0004_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.CharField(max_length=250, verbose_name='Value'),
        ),
    ]
