# Generated by Django 3.0.5 on 2020-07-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniker', '0006_commandgroups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommandGroup',
            new_name='ParameterGroup',
        ),
        migrations.AlterModelOptions(
            name='parametergroup',
            options={'verbose_name': 'Parameter group'},
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='command_group',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='job',
            name='command_group',
        ),
        migrations.AddField(
            model_name='job',
            name='groups',
            field=models.ManyToManyField(to='chroniker.ParameterGroup'),
        ),
    ]
