# Generated by Django 3.0.5 on 2020-07-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniker', '0007_parameter_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='monitor_description',
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text="An explanation of the job's purpose.", null=True, verbose_name='description'),
        ),
    ]
