# Generated by Django 3.0.6 on 2020-08-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chroniker', '0008_merge_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='ParameterGroup',
        ),
    ]
